# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='repo_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SVN', 'Subversion'), ('MERC', 'Mercurial'), ('GIT', 'Git')], default='NONE', max_length=4),
        ),
    ]
