# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0002_repo_repo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_version', models.PositiveIntegerField(default=0)),
                ('dependency_version', models.PositiveIntegerField(default=0)),
                ('master_last_edited', models.DateTimeField(null=True)),
                ('dependency_last_edited', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='edge',
            name='depend_file',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='main_file',
        ),
        migrations.AddField(
            model_name='file',
            name='last_edited',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='last_version',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='repo',
            name='root_path',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.AddField(
            model_name='depend',
            name='dependency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depend_to_set', to='spine_core.File'),
        ),
        migrations.AddField(
            model_name='depend',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depend_from_set', to='spine_core.File'),
        ),
    ]
