# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0004_auto_20160709_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='root_path',
            field=models.CharField(max_length=200),
        ),
    ]
