# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0005_auto_20160709_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depend',
            name='dependency_last_edited',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='depend',
            name='master_last_edited',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_edited',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
