# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0006_auto_20160709_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depend',
            old_name='dependency_last_edited',
            new_name='depend_last_edited',
        ),
        migrations.RenameField(
            model_name='depend',
            old_name='dependency_version',
            new_name='depend_version',
        ),
        migrations.RemoveField(
            model_name='depend',
            name='dependency',
        ),
        migrations.AddField(
            model_name='depend',
            name='depend',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='depend_set', to='spine_core.File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depend',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_set', to='spine_core.File'),
        ),
    ]
