# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0007_auto_20160709_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depend',
            old_name='depend',
            new_name='depend_file',
        ),
        migrations.RenameField(
            model_name='depend',
            old_name='master',
            new_name='master_file',
        ),
    ]
