# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0008_auto_20160709_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('3D Media', (('BLEND', 'Blender'), ('MA', 'Maya ASCII'), ('MB', 'Maya Binary'), ('OBJ', 'Wavefront'))), ('2D Media', (('PNG', 'Portable Network Graphics'), ('KRA', 'Krita'), ('XCF', 'GIMP'), ('PSD', 'Adobe Photoshop'), ('AI', 'Adobe Illustrator'), ('SVG', 'Scalable Vector Graphics'), ('TIFF', 'Tagged Image File Format'), ('JPG', 'JPEG'), ('EXR', 'OpenEXR'))), ('Text Data', (('TXT', 'Plain Text'), ('PY', 'Python'), ('MD', 'Markdown'), ('HTML', 'Hypertext Markup Language'), ('CSS', 'Cascading Style Sheets'))), ('OTHER', 'Other')], default='OTHER', max_length=8),
        ),
        migrations.AlterField(
            model_name='repo',
            name='repo_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SVN', 'Subversion'), ('MERC', 'Mercurial'), ('GIT', 'Git')], default='NONE', max_length=8),
        ),
    ]
