# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0009_auto_20160710_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='name',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
    ]
