# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0010_repo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=200),
        ),
    ]
