# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0011_auto_20160710_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='exists',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='file',
            name='md5_hash',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='size_in_bytes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
