# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0014_auto_20160712_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='project',
            new_name='projects',
        ),
    ]
