# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0018_auto_20160712_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depend',
            old_name='depend_last_edited',
            new_name='depend_modified',
        ),
        migrations.RenameField(
            model_name='depend',
            old_name='master_last_edited',
            new_name='master_modified',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='md5_hash',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='mime_type',
            new_name='mime',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='last_edited',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='exists',
            new_name='online',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='size_in_bytes',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='last_version',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='repo',
            old_name='root_path',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='repo',
            old_name='repo_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
