# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0022_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='comments',
            field=models.ManyToManyField(to='spine_core.Comment'),
        ),
    ]
