# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0023_asset_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depend',
            name='depend_file',
        ),
        migrations.RemoveField(
            model_name='depend',
            name='master_file',
        ),
        migrations.AddField(
            model_name='file',
            name='depends',
            field=models.ManyToManyField(to='spine_core.File'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='type',
            field=models.CharField(choices=[('NONE', 'Not Versioned'), ('SVN', 'Subversion'), ('MERC', 'Mercurial'), ('GIT', 'Git')], default='NONE', max_length=8),
        ),
        migrations.DeleteModel(
            name='Depend',
        ),
    ]
