# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0024_auto_20160721_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
