# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spine_core', '0025_auto_20160721_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='type',
            field=models.CharField(blank=True, choices=[('SVN', 'Subversion'), ('MERC', 'Mercurial'), ('GIT', 'Git')], max_length=8),
        ),
    ]
